@echo off
title GoAniWayneNathaniel2600 Version Checker
echo:
echo GoAniWayneNathaniel2600 Version Checker
echo Version 10.0
echo Build 22616.1.zn_release.240311-1605
echo Service Pack : 6
echo:
echo To see the installed Service packs. Press any key
echo:
pause
cls
echo:
echo Currently Installed Service Packs
echo Service Pack 0 (RTM) : Already Installed
echo Service Pack 1 (ESP) : Already Installed
echo Official Service Pack 1 (SP1) : Already Installed
echo Service Pack 2 : Already Installed
echo Service Pack 3 : Already Installed
echo Service Pack Cairo (MU) : Already Installed
echo Service Pack 5 : Already Installed
echo Service Pack 6 : Under Development Preview
echo:
pause
cls
echo:
echo What's new in this version
echo GAWN2600 Insider Preview 22616.1 (zn_release)
echo:
echo 1. New Exclusive Poses: Point At - Turn Head - Legs Bent
echo:
echo 2. The Creator of GAWN2600's character title when hovering on him in Character Browser
echo has been changed to "Nathan Animations"
echo:
pause
cls
echo:
echo Bugs and Quirks in this build.
echo:
echo There are no currently Detected Bugs and Quirks in this build.
echo:
pause
cls
echo:
echo Findings in this build.
echo:
echo There are currently no findings in this build.
echo:
pause