@echo off
title GoAniWayneNathaniel2600 Version Checker
echo GoAniWayneNathaniel2600 Version Checker
echo Version 10.0
echo Build 22538.1000.7.9.23.rs_prerelease.231121-1251
echo Service Pack : 6
echo Evaluation copy. Expires 9/15/2024
echo:
echo To see the installed Service packs. Press any key
echo:
pause
cls
echo:
echo Currently Installed Service Packs
echo Service Pack 6 : Under Construction
echo:
pause
cls
echo:
echo What's new in this version
echo GAWN2600 Insider Preview 22538.1000 (rs_prerelease)
echo:
pause