@Echo off
title  GoAniNathanYellowStar9600 Version Checker
echo GAWN2600 Pro Insider Preview
echo Version 2.1.1 (Build 25926.rs_prerelease.241010-0828)
echo:
echo New Features and Changes
echo:
echo 1. The title has been changed from GoAniWayneNathaniel2600 to GoAniNathanYellowStar9600.
echo:
echo 2. The "close node.bat" will now end Node.js process only instead of ending both Node.js and CMD process to avoid a bug
echo where the CMD window will not close.
echo:
pause
cls
echo Bug Fixes.
echo:
echo No bugfixes were implemented onto this build.
echo:
pause